ALTER TYPE care_journey_stage ADD VALUE IF NOT EXISTS 'ARRIVED';
ALTER TYPE care_journey_stage ADD VALUE IF NOT EXISTS 'CONSULTATION';
ALTER TYPE care_journey_stage ADD VALUE IF NOT EXISTS 'DIAGNOSTICS';
